<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SharpGameModes.Core</AssemblyName>
    <RootNamespace>SharpGameModes.Core</RootNamespace>
    <Description>Shared mode context service for SharpGameModes modules.</Description>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ModSharp.Sharp.Shared" PrivateAssets="all" ExcludeAssets="runtime" />
    <ProjectReference Include="../SharpGameModes.Contracts/SharpGameModes.Contracts.csproj" Private="false" ExcludeAssets="runtime" />
    <ProjectReference Include="../SharpGameModes.Domain/SharpGameModes.Domain.csproj" Private="false" ExcludeAssets="runtime" />
  </ItemGroup>
</Project>
