<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/SharpGameModes.Contracts/SharpGameModes.Contracts.csproj" />
    <ProjectReference Include="../../src/SharpGameModes.Domain/SharpGameModes.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="../../config/**/*" LinkBase="Config" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
